#!/usr/bin/env bash
# Idempotent bootstrap for the nncase Cloud Agent environment.
#
# Runs on Cursor's default Ubuntu 24.04 base image and prepares the full
# development stack from the checked-out source:
#   1. System toolchain: gcc/g++-14, Ninja, CMake, Python 3.10, .NET 7 SDK
#   2. Python 3.10 virtualenv + Conan 2.6.0
#   3. Native C++ library (conan install -> cmake build/install)
#   4. .NET 7 compiler (dotnet restore/build/publish)
#   5. Pinned Python runtime + test dependencies
#   6. A sourced env file wiring nncase into future shells
#
# Every step is guarded so re-running is cheap and safe.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export DEBIAN_FRONTEND=noninteractive
export CC=gcc-14 CXX=g++-14
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1
export DOTNET_ROOT=/usr/share/dotnet

VENV="$HOME/.venvs/nncase"
COMPILER_DLL="$REPO_ROOT/src/Nncase.Compiler/bin/Release/net7.0/linux-x64/publish/Nncase.Compiler.dll"

# --- 1. System toolchain -----------------------------------------------------
# GCC 14 is pinned by toolchains/x86_64-linux.profile.jinja; Python 3.10 matches
# CI and maximises wheel compatibility for the pinned test dependencies.
if ! command -v gcc-14 >/dev/null 2>&1 || ! command -v ninja >/dev/null 2>&1 \
   || ! command -v python3.10 >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends \
        ca-certificates curl gnupg git build-essential software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends \
        gcc-14 g++-14 ninja-build cmake \
        python3.10 python3.10-venv python3.10-dev
fi

# .NET 7 SDK (not packaged for Ubuntu 24.04; use the official install script).
if [ ! -x "$DOTNET_ROOT/dotnet" ]; then
    curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh
    chmod +x /tmp/dotnet-install.sh
    sudo /tmp/dotnet-install.sh --channel 7.0 --install-dir "$DOTNET_ROOT"
    sudo ln -sf "$DOTNET_ROOT/dotnet" /usr/local/bin/dotnet
    rm -f /tmp/dotnet-install.sh
fi

# --- 2. Python venv + Conan --------------------------------------------------
if [ ! -x "$VENV/bin/python" ]; then
    python3.10 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --upgrade pip
pip install "conan==2.6.0" wheel setuptools gitpython

# --- 3. Native C++ library ---------------------------------------------------
conan profile detect --force
conan remote add sunnycase https://conan.sunnycase.moe --index 0 --force
conan install . --build=missing -s build_type=Release \
    -pr:a=toolchains/x86_64-linux.profile.jinja \
    -o "&:runtime=False" -o "&:python=True" -o "&:tests=False" \
    -o "&:python_root=$VENV/bin"
cmake --preset conan-release
cmake --build build/Release --config Release
cmake --install build/Release --prefix install

# --- 4. .NET 7 compiler ------------------------------------------------------
dotnet restore -r linux-x64
dotnet build -c Release --no-restore
dotnet publish src/Nncase.Compiler -c Release --no-restore --sc false -r linux-x64

# The RID-specific restore rewrites tracked packages.lock.json files; discard
# those incidental changes so the working tree stays clean.
git checkout -- '**/packages.lock.json' 2>/dev/null || true

# --- 5. Python dependencies --------------------------------------------------
# Pinned model-framework deps used by the importer test suites (TensorFlow,
# PyTorch, ONNX, ncnn, ...). onnxsim/onnxruntime/pytest come along for the ride.
pip install -r requirements.test.txt

# --- 6. Wire nncase into future shells --------------------------------------
ENV_FILE="$HOME/.nncase_env.sh"
cat > "$ENV_FILE" <<EOF
# Auto-generated by .cursor/install.sh — activates the nncase dev environment.
source "$VENV/bin/activate"
export CC=gcc-14 CXX=g++-14
export DOTNET_ROOT=/usr/share/dotnet
export LD_LIBRARY_PATH="$REPO_ROOT/install/lib:\${LD_LIBRARY_PATH:-}"
export PYTHONPATH="$REPO_ROOT/install/lib:$REPO_ROOT/install/python:$REPO_ROOT/tests"
export NNCASE_COMPILER="$COMPILER_DLL"
EOF

for rc in "$HOME/.bashrc" "$HOME/.profile"; do
    touch "$rc"
    grep -qxF "source \"$ENV_FILE\"" "$rc" || echo "source \"$ENV_FILE\"" >> "$rc"
done

echo "nncase development environment ready."
echo "Compiler: $COMPILER_DLL"
