#!/usr/bin/env bash
# Idempotent repository bootstrap for the nncase Cloud Agent environment.
#
# Builds the full development stack from the checked-out source:
#   1. Python 3.10 virtualenv + Conan 2.6.0
#   2. Native C++ library (conan install -> cmake build/install)
#   3. .NET 7 compiler (dotnet restore/build/publish)
#   4. Python runtime + test dependencies
#   5. A sourced env file wiring nncase into future shells
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export CC=gcc-14 CXX=g++-14
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1

VENV="$HOME/.venvs/nncase"
COMPILER_DLL="$REPO_ROOT/src/Nncase.Compiler/bin/Release/net7.0/linux-x64/publish/Nncase.Compiler.dll"

# --- 1. Python venv + Conan --------------------------------------------------
if [ ! -x "$VENV/bin/python" ]; then
    python3.10 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --upgrade pip
pip install "conan==2.6.0" wheel setuptools gitpython

# --- 2. Native C++ library ---------------------------------------------------
conan profile detect --force
conan remote add sunnycase https://conan.sunnycase.moe --index 0 --force
conan install . --build=missing -s build_type=Release \
    -pr:a=toolchains/x86_64-linux.profile.jinja \
    -o "&:runtime=False" -o "&:python=True" -o "&:tests=False" \
    -o "&:python_root=$VENV/bin"
cmake --preset conan-release
cmake --build build/Release --config Release
cmake --install build/Release --prefix install

# --- 3. .NET 7 compiler ------------------------------------------------------
dotnet restore -r linux-x64
dotnet build -c Release --no-restore
dotnet publish src/Nncase.Compiler -c Release --no-restore --sc false -r linux-x64

# The RID-specific restore rewrites tracked packages.lock.json files; discard
# those incidental changes so the working tree stays clean.
git checkout -- '**/packages.lock.json' 2>/dev/null || true

# --- 4. Python dependencies --------------------------------------------------
# Pinned model-framework deps used by the importer test suites (TensorFlow,
# PyTorch, ONNX, ncnn, ...). onnxsim/onnxruntime/pytest come along for the ride.
pip install -r requirements.test.txt

# --- 5. Wire nncase into future shells --------------------------------------
ENV_FILE="$HOME/.nncase_env.sh"
cat > "$ENV_FILE" <<EOF
# Auto-generated by .cursor/install.sh — activates the nncase dev environment.
source "$VENV/bin/activate"
export CC=gcc-14 CXX=g++-14
export LD_LIBRARY_PATH="$REPO_ROOT/install/lib:\${LD_LIBRARY_PATH:-}"
export PYTHONPATH="$REPO_ROOT/install/lib:$REPO_ROOT/install/python:$REPO_ROOT/tests"
export NNCASE_COMPILER="$COMPILER_DLL"
EOF

for rc in "$HOME/.bashrc" "$HOME/.profile"; do
    touch "$rc"
    grep -qxF "source \"$ENV_FILE\"" "$rc" || echo "source \"$ENV_FILE\"" >> "$rc"
done

echo "nncase development environment ready."
echo "Compiler: $COMPILER_DLL"
