name: Upstream Sync

permissions:
    contents: write

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    sync_with_upstream:
        name: Sync with Upstream
        runs-on: ubuntu-latest
        strategy:
            matrix:
                branch: [master, "dev/3.0"]
        if: ${{ github.event.repository.fork }}

        steps:
            - name: Checkout target repo
              uses: actions/checkout@v3
              with:
                  # optional: set the branch to checkout,
                  # sync action checks out your 'target_sync_branch' anyway
                  ref:  ${{ matrix.branch }}
                
            - name: Sync Upstream
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                  upstream_sync_repo: kendryte/nncase
                  upstream_sync_branch: ${{ matrix.branch }}
                  target_sync_branch: ${{ matrix.branch }}
                  test_mode: false

            - name: Check for Failure
              if: failure()
              run: |
                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
                  exit 1
